# Generated by Django 5.0 on 2024-03-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
